# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
- task: Docker@2
  inputs:
    containerRegistry: 'prc0910-docker-hub'
    repository: 'contdock'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(1)(db8c547d-bfd5-4b98-8eff-e0bd9f18b34d)'
        appType: 'webAppContainer'
        WebAppName: 'DemoWebappDocker'
        DockerNamespace: 'demowebappdocker-eyergge3d3hdc0fj.westeurope-01.azurewebsites.net'
        DockerRepository: 'Dockerfile'
